const {
  SlashCommandBuilder,
  PermissionFlagsBits,
  ChannelType,
  MessageFlags,
} = require("discord.js");
const { db, stmts } = require("../../db");
const { refreshJudgeHub } = require("../../utils/helpers");

const insertMany = db.transaction((rows) => {
  for (const row of rows) stmts.insertSubmission.run(row);
});

module.exports = {
  data: new SlashCommandBuilder()
    .setName("event-seed")
    .setDescription("Fill an event with fake test submissions")
    .addIntegerOption((opt) =>
      opt
        .setName("event-id")
        .setDescription("The event ID to seed")
        .setRequired(true),
    )
    .addIntegerOption((opt) =>
      opt
        .setName("count")
        .setDescription("Number of fake submissions to add (1–25)")
        .setRequired(true)
        .setMinValue(1)
        .setMaxValue(25),
    )
    .setDefaultMemberPermissions(PermissionFlagsBits.Administrator),

  async execute(interaction) {
    await interaction.deferReply({ flags: MessageFlags.Ephemeral });

    const eventId = interaction.options.getInteger("event-id");
    const count = interaction.options.getInteger("count");
    const event = stmts.getEvent.get(eventId);

    if (!event) return interaction.editReply("Event not found.");
    if (event.status === "archived")
      return interaction.editReply("Cannot seed an archived event.");
    if (!event.submission_channel_id)
      return interaction.editReply("This event has no submission channel.");

    const guild = interaction.guild;
    let subChannel;
    try {
      subChannel = await guild.channels.fetch(event.submission_channel_id);
    } catch {
      return interaction.editReply("Could not fetch the submission channel.");
    }

    const { count: existing } = stmts.countSubmissions.get(eventId);
    const startNum = existing + 1;

    // Create all threads in parallel
    const results = await Promise.allSettled(
      Array.from({ length: count }, (_, i) => {
        const entryNum = startNum + i;
        return subChannel.threads
          .create({
            name: `#${entryNum} - bot`,
            type: ChannelType.PrivateThread,
            autoArchiveDuration: 10080,
            invitable: false,
            reason: `Test seed for event: ${event.name}`,
          })
          .then((thread) => ({ entryNum, thread }));
      }),
    );

    // Batch-insert all successful threads in one transaction
    const rows = [];
    for (const r of results) {
      if (r.status === "rejected") {
        console.error("[seed] thread create failed:", r.reason);
        continue;
      }
      const { entryNum, thread } = r.value;
      rows.push({
        event_id: eventId,
        user_id: `bot-${entryNum}`,
        thread_id: thread.id,
        codename: `bot-${entryNum}`,
        entry_num: entryNum,
        title: `bot-${entryNum}`,
        description: "Test submission generated by /event-seed.",
        link: null,
        category: "General",
      });
    }

    insertMany(rows);
    await refreshJudgeHub(guild, stmts.getEvent.get(eventId), stmts);

    return interaction.editReply(
      `Created **${rows.length}** test submission${rows.length !== 1 ? "s" : ""} for **${event.name}**.`,
    );
  },
};
